name: XPSystem
main: misael38\XPSystem\Main
version: 2.0.0
api: [3.0.0]
author: misael38
description: Open the XPSystem Menu for player and Admin!
website: https://github.com/misael38/XPSystem
permissions:
  xp.all:
    description: "Allows you to use all XPSystem commands"
    children:
      xp.command.admin:
        description: "Allows you use /xp admin command."
      xp.command.add:
        description: "Allows you to add a xp level to other player."	
      xp.command.set:
        description: "Allows you to set other player is xp level."
      xp.command.remove:
        description: "Allow you to remover other player is xp level."
