---
#MORE ABOUT ME:
#github: https://github.com/misael38
#Instagram: https://instagram.com/misaelimanuell?igshid=9vcjegn0npgg (@misaelimanuell)
#Discord : Misaelx_#8452

#The price per xp level to buy it
price_buy: 1000

#The price per xp level to sell it
price_sell: 1000
...
